extends: 'eslint:recommended'
env:
  commonjs: true
  es6: true
  node: true
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
